# Generated by Django 4.0.6 on 2022-07-27 06:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Information',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
                ('age', models.IntegerField()),
                ('phonenum', models.CharField(default='', max_length=70)),
                ('aadharno', models.CharField(default='', max_length=70)),
                ('gender', models.CharField(default='', max_length=70)),
                ('fathername', models.CharField(default='', max_length=500)),
                ('match', models.BooleanField()),
            ],
        ),
    ]
