# Generated by Django 4.0.1 on 2022-07-29 14:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='information',
            name='aadharno',
        ),
        migrations.RemoveField(
            model_name='information',
            name='fathername',
        ),
        migrations.RemoveField(
            model_name='information',
            name='gender',
        ),
    ]
